---
name: CI

on:
  push:
    tags: ["release/v*"]
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Tests on Python"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: "actions/checkout@v3"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Python
        run: uv python install
      - name: Install project
        run: uv sync --group test
      - name: "Run tests"
        run: uv run pytest tests
      - name: "Check coverage"
        run: uv run coverage report --show-missing --fail-under=100

  package:
    name: "Build Package Distributions"
    needs: tests
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build package
        run: uv build --wheel
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/release/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
