name: Bump version and publish

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Bump type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-and-publish:
    name: Bump version and publish 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Bump version
        id: bump
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.bump-type }}

      - name: Check
        if: steps.bump.outputs.bumped == 'false'
        run: |
          echo "Version was not bumped"
          exit 1

      - name: Install uv
        uses: astral-sh/setup-uv@v5 
 
      - name: Build package
        run: uv build --wheel
 
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
